name: build-plugin
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/EdgeAuth/EdgeAuth.csproj

      - name: Build (Release)
        run: dotnet build src/EdgeAuth/EdgeAuth.csproj -c Release --no-restore

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail
          rm -rf dist
          mkdir -p dist/EdgeAuth
          cp src/EdgeAuth/bin/Release/net8.0/EdgeAuth.dll dist/EdgeAuth/
          cp src/EdgeAuth/plugin.json dist/EdgeAuth/
          # ensure no old zip left around, then zip ONLY the EdgeAuth folder
          rm -f dist/edgeauth-*.zip
          ( cd dist && zip -r -9 "edgeauth-${GITHUB_SHA}.zip" EdgeAuth )

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: edgeauth-${{ github.sha }}
          path: dist/edgeauth-*.zip
          if-no-files-found: error
          retention-days: 7
