name: release
on:
  push:
    tags:
      - 'v*'   # push e.g. v0.1.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create a release
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/EdgeAuth/EdgeAuth.csproj

      - name: Build (Release)
        run: dotnet build src/EdgeAuth/EdgeAuth.csproj -c Release --no-restore

      - name: Stage plugin files
        shell: bash
        run: |
          set -euo pipefail
          rm -rf dist
          mkdir -p dist/EdgeAuth
          cp src/EdgeAuth/bin/Release/net8.0/EdgeAuth.dll dist/EdgeAuth/
          cp src/EdgeAuth/plugin.json dist/EdgeAuth/
          ( cd dist && zip -r -9 "edgeauth-${GITHUB_REF_NAME}.zip" EdgeAuth )

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/edgeauth-*.zip
          generate_release_notes: true
